### ISSUE TITLE
Автовставка промокода

### ISSUE THREAD

**Issue by Botan626** [MAX1MDEV/FreeruCompanion#1]
Возможно добавить автовставку промокода в поле после того как он был скопирован?

**Comment by MAX1MDEV** [comment]
> Возможно добавить автовставку промокода в поле после того как он был скопирован?

Да, возможно, сейчас этим займусь.

**Comment by MAX1MDEV** [comment]
> Возможно добавить автовставку промокода в поле после того как он был скопирован?

Пробовал, не получалось, каждый раз писало о том, что промокод закончился. Либо кто-то его подбирает автоматически, либо где-то его сливают.

**Comment by Botan626** [comment]
> каждый раз писало о том, что промокод закончился

А что, большая задержка была между нажатием на кнопку копировать и появлением промокода в поле?

Я не имел в виду активировать его тоже, только чтобы он был вставлен в это поле:
![image](https://github.com/user-attachments/assets/bcc0bf7a-3582-4ff5-82a0-434347cd40d0)
после нажатия на эту кнопку ![image](https://github.com/user-attachments/assets/2b6eb04c-ad28-4ac7-a865-7bdea821cadf)

Активировать промо вручную мышкой после вставки.
